# Source: https://github.com/actions/cache/blob/81382a721fc89d96eca335d0c3ba33144b2baa9d/tips-and-workarounds.md#force-deletion-of-caches-overriding-default-cache-eviction-policy
name: Cleanup branch caches

description: An action to delete all caches on a branch.

inputs:
  branch-name:
    description: The branch to clean up.
    default: ${{ github.ref }}
    required: false
  github-token:
    description: The token used to access the repository.
    required: true
  repo-url:
    description: The URL to the repository.
    default: ${{ github.repository }}
    required: false

runs:
  using: composite

  steps:
    - name: cleanup
      id: cleanup
      run: |
        gh extension install actions/gh-actions-cache
        
        repo="${{ inputs.repo-url }}"
        branch="${{ inputs.branch-name }}"
        
        printf "Fetching list of cache keys for branch %s..." "${branch}"
        cache_keys_for_pr=( $( \
          gh actions-cache \
            --repo "${repo}" \
            --branch "${branch}" \
            list \
            | cut -f 1) \
        )
        echo " Done."
        
        ## Setting this to not fail the workflow while deleting cache keys. 
        set +e
        if [[ -n "${cache_keys_for_pr[*]}" ]]
        then
          echo "Found the following cache keys:"
          for cache_key in "${cache_keys_for_pr[@]}"
          do
            echo "  ${cache_key}"
          done
          echo "Starting deletion of caches"
          for cache_key in "${cache_keys_for_pr[@]}"
          do
            printf "  Deleting cache with key %s..." "${cache_key}"
            gh actions-cache delete \
              --repo "${repo}" \
              --branch "${branch}" \
              --confirm \
              "${cache_key}" \
              1> /dev/null
            echo " Done."
          done
          echo "All caches deleted."
        else
          echo "No caches on branch ${branch} found. Nothing to delete."
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}