ifndef::rootdir[]
:toc:
:toclevels: 4
:rootdir: ../../../../../../../../..
endif::[]

= Inputs

[cols=4*,options=header]
|===
| name
| description
| Required?
| default value

4+^| **GraalVM configuration**

a|
----
graalvm-distribution
----
| The GraalVM Distribution to use.
| ❌
a|
----
mandrel
----

a|
----
graalvm-version
----
| The GraalVM Distribution version to use.
| ❌
a|
----
mandrel-23.1.2.0-Final
----

a|
----
java-version
----
| The Java version of the GraalVM Distribution.
| ❌
a|
----
'21'
----

4+^| **Maven execution configuration**

a|
----
maven-opts
----
| Options passed to the maven command.
| ❌
a|
----
--batch-mode
--color always
----

a|
----
maven-targets
----
| The maven targets (goals and/or phases) to execute.
| ❌
a|
----
verify
----

4+^| **Artifact-related configuration**

4+^| Upload

a|
----
artifact-retention-days
----
| Duration in days after which the artifacts will expire.
| ❌
a|
----
'2'
----

a|
----
compiled-classes-artifact-name
----
| The name for the artifact holding all compiled classes.
| ❌
a|
----
compiled-classes
----

a|
----
fast-jar-artifact-name
----
| The name for the artifact holding the fast jar.
| ❌
a|
----
fast-jar
----

a|
----
fast-jar-artifact-path
----
| The path to the directory holding the fast-jar.
| ❌
a|
----
target/quarkus-app
----

a|
----
jars-artifact-name
----
| The name for the artifact holding all jars.
| ❌
a|
----
jars
----

a|
----
maven-state-artifact-name
----
| The name for the artifact holding the maven state.
| ❌
a|
----
maven-state
----

a|
----
test-report-artifact-name
----
| The name for the artifact holding the test report.
| ❌
a|
----
test-report-jvm
----

a|
----
test-report-artifact-path
----
| The path to the test report.
| ❌
a|
----
'**/target/**/TEST*.xml'
----

4+^| **PR commenting**

a|
----
comment-enabled
----
| Whether a comment on the corresponding PR (if any) should be posted.
| ❌
a|
----
'true'
----
|===