name: Build and Test (Native)

description: An action to build and test a Quarkus application in Native Mode

inputs:
  graalvm-distribution:
    description: The GraalVM Distribution to use.
    default: mandrel
    required: true
  graalvm-version:
    description: The GraalVM Distribution version to use.
    default: mandrel-23.1.2.0-Final
    required: true
  java-version:
    description: The Java version of the GraalVM Distribution.
    default: '21'
    required: true

  maven-opts:
    description: Options passed to the maven command.
    default: >-
      --batch-mode
      --color always
    required: true
  maven-targets:
    description: The maven targets (goals and/or phases) to execute.
    default: verify
    required: true

  artifact-retention-days:
    description: Duration in days after which the artifacts will expire.
    default: '2'
    required: true
  executable-artifact-name:
    description: The name for the artifact holding the executable.
    default: executable
    required: true
  executable-artifact-path:
    description: The path to the executable and related files (if any).
    default: |-
      target/*-runner
      target/*.so
    required: true
  test-report-artifact-name:
    description: The name for the artifact holding the test report.
    default: test-report-native
    required: true
  test-report-artifact-path:
    description: The path to the test report.
    default: '**/target/**/TEST*.xml'
    required: true

runs:
  using: composite

  steps:
    - name: Build and Test
      id: build-and-test
      uses: turing85/shared-github-workflows/.github/actions/java/maven/build@main
      with:
        graalvm-distribution: ${{ inputs.graalvm-distribution }}
        graalvm-version: ${{ inputs.graalvm-version }}
        java-version: ${{ inputs.java-version }}

        maven-opts: ${{ inputs.maven-opts }}
        maven-targets: ${{ inputs.maven-targets }}

    - name: Upload executable
      id: upload-executable
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        if-no-files-found: error
        name: ${{ inputs.executable-artifact-name }}
        path: ${{ inputs.executable-artifact-path }}
        retention-days: 2

    - name: Upload Test Report
      id: upload-test-report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        if-no-files-found: error
        name: ${{ inputs.test-report-artifact-name }}
        path: ${{ inputs.test-report-artifact-path }}
        retention-days: 2