name: Populate Cache

description: An action to populate the maven cache.

inputs:
  graalvm-distribution:
    description: The distribution of GraalVM to use
    default: mandrel
    required: true
  graalvm-version:
    description: The version of the GraalVM distribution to use
    default: 23.1.2.0-Final
    required: true
  java-version:
    description: The Java version to use
    default: '21'
    required: true

  maven-opts:
    description: Options passed to the maven command.
    default: >-
      --batch-mode
      --color always
    required: true
  maven-targets:
    description: The maven targets (goals and/or phases) to execute.
    default: verify
    required: true
runs:
  using: composite

  steps:
    - name: Set up ${{ inputs.graalvm-distribution }} ${{ inputs.graalvm-version }} (Java ${{ inputs.java-version }})
      id: setup
      uses: graalvm/setup-graalvm@v1
      with:
        cache: 'maven'
        distribution: ${{ inputs.graalvm-distribution }}
        java-version: ${{ inputs.java-version }}
        version: ${{ inputs.graalvm-version }}

    - name: Populate Cache
      id: populate-cache
      if: ${{ steps.setup.outputs.cache-hit != 'true' }}
      shell: sh
      run: |
        ./mvnw \
          ${{ inputs.maven-opts }} \
          ${{ inputs.maven-targets }}
