name: Nightly CVE Scan

on:
  workflow_call:
    inputs:
      graalvm-distribution:
        description: The GraalVM Distribution to use
        default: mandrel
        required: false
        type: string
      graalvm-version:
        description: the GraalVM Distribution version to use
        default: mandrel-23.1.2.0-Final
        required: false
        type: string
      java-version:
        description: The Java version of the GraalVM Distribution
        default: 21
        required: false
        type: string

      maven-opts:
        description: Options passed to the maven command for Cache population.
        default: >-
          --batch-mode
          --color always
        required: false
        type: string
      maven-targets:
        description: The maven targets (goals and/or phases) to execute for Cache population.
        default: verify
        required: false
        type: string

permissions:
  actions: write
  checks: write

jobs:
  populate-cache:
    name: Populate Cache
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        id: git-checkout
        uses: actions/checkout@v4

      - name: Git Checkout shared workflows
        id: git-checkout-shared-workflows
        uses: actions/checkout@v4
        with:
          path: shared-github-workflows
          ref: main
          repository: turing85/shared-github-workflows

      - name: Populate Cache
        id: populate-cache
        uses: ./shared-github-workflows/.github/actions/java/maven/populate-cache
        with:
          graalvm-distribution: ${{ inputs.graalvm-distribution }}
          graalvm-version: ${{ inputs.graalvm-version }}
          java-version: ${{ inputs.java-version }}

          maven-opts: ${{ inputs.maven-opts }}
          maven-targets: ${{ inputs.maven-targets }}
