name: Quarkus Build

on:
  workflow_call:
    inputs:
      graalvm-distribution:
        description: The GraalVM Distribution to use
        default: mandrel
        required: false
        type: string
      graalvm-version:
        description: the GraalVM Distribution version to use
        default: mandrel-23.1.2.0-Final
        required: false
        type: string
      java-version:
        description: The Java version of the GraalVM Distribution
        default: 21
        required: false
        type: string

      maven-opts-jvm:
        description: Options passed to the maven command for the JVM Build.
        default: >-
          --batch-mode
          --color always
        required: false
        type: string
      maven-opts-native:
        description: Options passed to the maven command for the Native Build.
        default: >-
          --batch-mode
          --color always
        required: false
        type: string
      maven-targets-jvm:
        description: The maven targets (goals and/or phases) to execute for the JVM build.
        default: org.owasp:dependency-check-maven:check
        required: false
        type: string
      maven-targets-native:
        description: The maven targets (goals and/or phases) to execute for the native build.
        default: verify
        required: false
        type: string

      comment-enabled:
        description: Whether a comment on the corresponding PR (if any) should be posted
        default: true
        required: false
        type: boolean

env:
  DOCKER_BUILDKIT: 1

permissions:
  actions: write
  checks: write
  pull-requests: write

jobs:

  build-and-test-jvm:
    name: Build and Test (JVM)
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        id: git-checkout
        uses: actions/checkout@v4

      - name: Build and Test
        id: build-and-test
        uses: turing85/shared-github-workflows/.github/actions/java/maven/quarkus/single-module/build-and-test-jvm@main
        with:
          graalvm-distribution: ${{ inputs.graalvm-distribution }}
          graalvm-version: ${{ inputs.graalvm-version }}
          java-version: ${{ inputs.java-version }}

          maven-opts: ${{ inputs.maven-opts-jvm }}
          maven-targets: ${{ inputs.maven-targets-jvm }}

  build-and-test-native:
    name: Build and Test (Native)
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        id: git-checkout
        uses: actions/checkout@v4

      - name: Build and Test
        id: build-and-test
        uses: turing85/shared-github-workflows/.github/actions/java/maven/quarkus/single-module/build-and-test-native@main
        with:
          graalvm-distribution: ${{ inputs.graalvm-distribution }}
          graalvm-version: ${{ inputs.graalvm-version }}
          java-version: ${{ inputs.java-version }}

          maven-opts: ${{ inputs.maven-opts-native }}
          maven-targets: ${{ inputs.maven-targets-native }}

          comment-enabled: ${{ inputs.comment-enabled }}